
[deployment]
  target = "cloudflare-pages"

[profile]
  name = "Phearak S. Tha"
  bio = "Software Engineer • Photographer"

[social]
  twitter = "thasophearak"
  github = "thasophearak"
  youtube = "thasophearak"
